Architecture refactor
crendo11/AndroidBootcamp pull request #2
Opened 2022-06-16 15:52 UTC by crendo11

Refactored architecture and connected with search and home fragment to extract movie data from the data source.

2022-06-16 16:29 UTC, estebanhiguitad requested changes

2022-06-16 16:29 UTC, estebanhiguitad commented on Week5/IMDB_project/app/src/main/java/com/example/imdb_project/HorizontalMovieListAdapter.kt
>  import android.view.ViewGroup
Agregar archivo a uno de los paquetes de la arquitectura

2022-06-16 16:29 UTC, estebanhiguitad commented on Week5/IMDB_project/app/src/main/java/com/example/imdb_project/MovieListAdapter.kt
>  import android.view.ViewGroup
Agregar archivo a uno de los paquetes de la arquitectura

2022-06-16 16:29 UTC, estebanhiguitad commented on Week5/IMDB_project/app/src/main/java/com/example/imdb_project/LoginActivity.kt
>  import android.os.Bundle
Agregar archivo a uno de los paquetes de la arquitectura

2022-06-16 16:29 UTC, estebanhiguitad commented on Week5/IMDB_project/app/src/main/java/com/example/imdb_project/Movies.kt
>  package com.example.imdb_project
Agregar archivo a uno de los paquetes de la arquitectura

2022-06-16 16:29 UTC, estebanhiguitad commented on Week5/IMDB_project/app/src/main/java/com/example/imdb_project/data/datasources/MoviesDataSourceImpl.kt
> +class MoviesDataSourceImpl: MoviesDataSource {
Buena implementación

2022-06-16 16:29 UTC, estebanhiguitad commented on Week5/IMDB_project/app/src/main/java/com/example/imdb_project/data/repositories/MoviesRepositoryImpl.kt
> +        dto.forEach{ movieDto ->
Buena aplicación de lo que vimos ayer. 
Ahora se puede hacer una clase aparte que solo tenga la responsabilidad de hacer el mapper, así el repositorio solo se encarga de hacer la gestión

2022-06-16 16:29 UTC, estebanhiguitad commented on Week5/IMDB_project/app/src/main/java/com/example/imdb_project/ui/presentation/fragments/SearchFragment.kt
> +        _binding = SearchFragmentBinding.inflate(inflater, container, false)
Separar acciones en oncreateView en métodos con las responsabilidades definidas. Al final puede quedar algo como esto:

```
override fun onCreateView( ...): View {  
    configView()
    setListeners()
    doSomethingElse()
}
```

2022-06-18 22:44 UTC, crendo11 commented on Week5/IMDB_project/app/src/main/java/com/example/imdb_project/MovieListAdapter.kt
>  import android.view.ViewGroup
Lo moví al paquete del UI

2022-06-18 22:45 UTC, crendo11 commented on Week5/IMDB_project/app/src/main/java/com/example/imdb_project/LoginActivity.kt
>  import android.os.Bundle
Lo moví al paquete del UI

2022-06-18 22:45 UTC, crendo11 commented on Week5/IMDB_project/app/src/main/java/com/example/imdb_project/Movies.kt
>  package com.example.imdb_project
Esta clase ya no la estoy usando, la eliminé

2022-06-18 22:45 UTC, crendo11 commented on Week5/IMDB_project/app/src/main/java/com/example/imdb_project/HorizontalMovieListAdapter.kt
>  import android.view.ViewGroup
Lo moví al paquete del UI

2022-06-18 22:52 UTC, crendo11 commented on Week5/IMDB_project/app/src/main/java/com/example/imdb_project/data/repositories/MoviesRepositoryImpl.kt
> +        dto.forEach{ movieDto ->
Cree la clase MovieListMapper con un método que implementa este código. Y lo llamo desde el Repository

2022-06-18 23:10 UTC, crendo11 commented on Week5/IMDB_project/app/src/main/java/com/example/imdb_project/ui/presentation/fragments/SearchFragment.kt
> +        _binding = SearchFragmentBinding.inflate(inflater, container, false)
Creé los métodos _initViewBinding()_ y _configureRecyclerViews()_ y los llamé en el _onCreateView()_.
No sé si de pronto es necesario refactorizar más el _configureRecyclerViews()_

2022-06-21 12:07 UTC, estebanhiguitad approved these changes

2022-06-21 12:07 UTC, merged